### ISSUE TITLE
Hay lógica repetida entre estos dos fragmentos de código

### ISSUE THREAD

**Issue by natoszme** [Casorey/Tp-wollok#6]
https://github.com/Casorey/Tp-wollok/blob/d2e7c5c3ee2c1e0ed919e92ab77bd273a65906ef/src/classes.wlk#L49

https://github.com/Casorey/Tp-wollok/blob/master/src/classes.wlk#L79

**Comment by Casorey** [comment]
resuelto creo? no estoy seguro si no rompo encapsulamiento ni nada, pero creo que queda bien asi?
